apiVersion: v1
kind: Service
metadata:
  name: jky
  labels:
    app: jky
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: jky
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jky
  labels:
    app: jky
    version: v1
spec:
  selector:
    matchLabels:
      app: jky
      version: v1
  template:
    metadata:
      labels:
        app: jky
        version: v1
    spec:
      containers:
        - image: ghrc.io/oneadm/jky:1.0
          imagePullPolicy: Always
          name: jky
          command: [ "/bin/sh", "-c", "env" ]
          envFrom:
            - configMapRef:
                name: java-configmap
            - configMapRef:
                name: jky
          command: ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
          ports:
            - containerPort: 80
              name: http
