name: Deploy to K3s

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build And Push
        run: |
          docker build --platform=linux/amd64 -t ghrc.io/oneadm/jky:1.0 .
          docker push ghrc.io/oneadm/jky:1.0
      - name: Configure kubectl
        uses: steebchen/kubectl@v2.0.0
      - name: Deploy kubectl
        run: |
          kubectl config set-cluster k3s --server=https://119.91.222.75:6443 --insecure-skip-tls-verify=true
          kubectl config set-credentials  k3s --token=${{ secrets.K3S_TOKEN }}
          kubectl config set-context k3s --cluster=k3s --user=k3s
          kubectl config use-context k3s
          kubectl apply -n dev  -f  ./Kubernetes-dev.yaml
          kubectl delete  -n dev -f ./Kubernetes-dev.yaml
          kubectl apply -n dev  -f  ./Kubernetes-dev.yaml
         

      
